[package]
name = "laptop-backup"
version = "0.0.0"
edition = "2024"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1


[dependencies]
tar = "0.4.44"
chrono = "0.4"
walkdir = "2"
age   = { version = "0.11", features = ["armor"] }
anyhow = "1.0.100"
